import { StyleSheet } from 'react-native';
import { colors } from '@/theme/theme';

export const styles = StyleSheet.create({
  fill: { flex: 1 },
  stretch: { alignSelf: 'stretch' },
  actionTop18: { marginTop: 18 },
  actionTop20: { marginTop: 20 },
  page: { paddingHorizontal: 22, paddingTop: 12, paddingBottom: 32 },
  grades: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  grade: { width: '31%', minHeight: 48, backgroundColor: colors.pale, borderRadius: 12, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4 },
  gradeDisabled: { opacity: 0.45 },
  gradeText: { color: colors.forest, fontSize: 11, fontWeight: '700', textAlign: 'center' },
  countCard: {
    borderRadius: 18,
    backgroundColor: colors.pale,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    marginBottom: 20,
    flexWrap: 'wrap',
  },
  countText: { fontWeight: '800', fontSize: 16, color: colors.ink },
  countSub: { color: colors.muted, fontSize: 12, marginLeft: 'auto' },
  search: {
    minHeight: 52,
    borderRadius: 15,
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    gap: 9,
    marginBottom: 14,
  },
  searchInput: { flex: 1, fontSize: 15, color: colors.ink, paddingVertical: 7 },
  filters: { gap: 8, paddingBottom: 20, paddingRight: 22 },
  filter: {
    paddingHorizontal: 16,
    height: 39,
    borderRadius: 20,
    backgroundColor: colors.surface,
    justifyContent: 'center',
    borderColor: colors.line,
    borderWidth: 1,
  },
  filterActive: { backgroundColor: colors.forest, borderColor: colors.forest },
  filterText: { fontSize: 12, fontWeight: '700', color: colors.muted },
  filterTextActive: { color: colors.surface },
  progressCard: {
    backgroundColor: colors.forest,
    borderRadius: 24,
    padding: 22,
    marginBottom: 30,
    gap: 8,
    overflow: 'hidden',
  },
  progressTitle: {
    fontSize: 23,
    fontWeight: '800',
    color: colors.surface,
    marginTop: 4,
  },
  progressSubtitle: {
    fontSize: 13,
    color: '#D9EEE1',
    lineHeight: 20,
    maxWidth: '75%',
  },
  progressDecoration: {
    position: 'absolute',
    right: 20,
    top: 27,
    width: 67,
    height: 67,
    borderRadius: 24,
    backgroundColor: '#FFFFFF19',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modeCard: {
    flexDirection: 'row',
    gap: 14,
    alignItems: 'center',
    padding: 14,
    borderRadius: 21,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.line,
  },
  flashMode: { backgroundColor: colors.pale },
  quizMode: { backgroundColor: colors.surface },
  quizArt: { backgroundColor: colors.lime },
  modeArt: {
    width: 76,
    height: 90,
    borderRadius: 17,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modeArtText: { fontSize: 28, color: colors.forest, fontWeight: '800' },
  modeTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.ink,
    marginTop: 4,
  },
  modeDescription: {
    fontSize: 12,
    lineHeight: 18,
    color: colors.muted,
    marginTop: 4,
  },
  modeLink: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.success,
    marginTop: 9,
  },
  quote: {
    textAlign: 'center',
    color: colors.subtle,
    fontSize: 13,
    fontStyle: 'italic',
    marginTop: 26,
  },
  counter: { fontSize: 13, fontWeight: '800', color: colors.forest },
  progressTrack: {
    height: 7,
    borderRadius: 6,
    backgroundColor: colors.line,
    overflow: 'hidden',
    marginBottom: 23,
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.success,
    borderRadius: 6,
  },
  flashcard: {
    height: 330,
    borderRadius: 26,
    backgroundColor: colors.forest,
    padding: 22,
    justifyContent: 'space-between',
    marginBottom: 13,
  },
  flippedCard: { backgroundColor: colors.lime },
  flashcardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  flipPrompt: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  flashcardSmall: {
    fontSize: 11,
    color: colors.lime,
    fontWeight: '800',
    letterSpacing: 1,
  },
  flashcardCenter: { alignItems: 'center', gap: 13 },
  flashcardType: { color: colors.lime, fontSize: 14 },
  flashcardWord: {
    color: colors.surface,
    fontSize: 35,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 43,
  },
  flashcardExample: { color: '#D9EEE1', fontSize: 13, textAlign: 'center' },
  hint: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 20,
    textAlign: 'center',
    marginBottom: 19,
  },
  textAction: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  textActionLabel: { fontSize: 14, fontWeight: '700', color: colors.forest },
  question: {
    backgroundColor: colors.forest,
    borderRadius: 22,
    minHeight: 139,
    padding: 18,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 7,
    marginBottom: 21,
  },
  questionLabel: {
    fontSize: 11,
    letterSpacing: 1.2,
    fontWeight: '800',
    color: colors.lime,
  },
  questionWord: { fontSize: 30, fontWeight: '800', color: colors.surface },
  questionIpa: { fontSize: 14, color: '#D9EEE1' },
  answerList: { gap: 9 },
  answer: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 16,
    minHeight: 63,
    paddingHorizontal: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  answerCorrect: { borderColor: colors.success, backgroundColor: '#E7F5E8' },
  answerWrong: { borderColor: colors.error, backgroundColor: '#FFF1ED' },
  answerLetter: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: colors.pale,
    justifyContent: 'center',
    alignItems: 'center',
  },
  answerLetterText: { fontSize: 13, fontWeight: '800', color: colors.forest },
  answerText: { flex: 1, fontWeight: '700', fontSize: 14, color: colors.ink },
  feedback: {
    backgroundColor: '#FFF1ED',
    padding: 14,
    borderRadius: 15,
    marginTop: 13,
  },
  feedbackCorrect: { backgroundColor: '#E7F5E8' },
  feedbackText: {
    fontSize: 13,
    lineHeight: 20,
    color: colors.ink,
    fontWeight: '700',
  },
  finish: { paddingTop: 65, alignItems: 'center', gap: 13 },
  finishIcon: {
    width: 74,
    height: 74,
    borderRadius: 26,
    backgroundColor: colors.lime,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 7,
  },
  finishTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.ink,
    textAlign: 'center',
  },
  finishDescription: {
    fontSize: 14,
    lineHeight: 21,
    color: colors.muted,
    textAlign: 'center',
  },
  score: {
    width: 164,
    height: 164,
    borderRadius: 82,
    borderWidth: 11,
    borderColor: colors.lime,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 24,
  },
  scoreValue: { fontSize: 36, fontWeight: '800', color: colors.forest },
  scoreCaption: { fontSize: 13, color: colors.muted },
  historyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
    borderRadius: 17,
    padding: 10,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    marginBottom: 10,
  },
  historyImage: { width: 66, height: 66, borderRadius: 12 },
  historyDate: { fontSize: 11, fontWeight: '800', color: colors.success },
  historyTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.ink,
    marginTop: 3,
  },
  historyCaption: { fontSize: 12, color: colors.muted, marginTop: 3 },
});
