import { StyleSheet } from 'react-native';
import { colors } from '@/theme/theme';

export const styles = StyleSheet.create({
  fill: { flex: 1 },
  reviewCopy: { flex: 1, gap: 5 },
  actionTop20: { marginTop: 20 },
  actionTop12: { marginTop: 12 },
  page: { paddingHorizontal: 22, paddingTop: 12, paddingBottom: 32 },
  homeTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 32,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: colors.pale,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { fontSize: 18, fontWeight: '800', color: colors.forest },
  greeting: { gap: 9, marginBottom: 23 },
  greetingTitle: {
    fontSize: 34,
    lineHeight: 40,
    fontWeight: '800',
    letterSpacing: -1.2,
    color: colors.ink,
  },
  description: { color: colors.muted, fontSize: 14, lineHeight: 21 },
  hero: {
    minHeight: 226,
    borderRadius: 26,
    backgroundColor: colors.forest,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    overflow: 'hidden',
  },
  heroCopy: { flex: 1, alignItems: 'flex-start', gap: 18, zIndex: 1 },
  heroPill: {
    paddingHorizontal: 9,
    paddingVertical: 7,
    backgroundColor: colors.lime,
    borderRadius: 20,
    flexDirection: 'row',
    gap: 4,
    alignItems: 'center',
  },
  heroPillText: {
    color: colors.forest,
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  heroTitle: {
    color: colors.surface,
    fontWeight: '800',
    fontSize: 23,
    lineHeight: 29,
    letterSpacing: -0.6,
  },
  heroAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    borderRadius: 13,
    backgroundColor: colors.lime,
    paddingVertical: 9,
    paddingHorizontal: 10,
  },
  heroActionText: { fontSize: 12, fontWeight: '800', color: colors.forest },
  heroPicture: { width: '39%', alignItems: 'center', justifyContent: 'center' },
  heroImage: { width: '100%', height: 162, borderRadius: 17 },
  heroLabel: {
    position: 'absolute',
    left: -8,
    bottom: 9,
    flexDirection: 'row',
    gap: 3,
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 10,
    paddingHorizontal: 7,
    paddingVertical: 6,
  },
  heroLabelText: { color: colors.forest, fontSize: 10, fontWeight: '800' },
  demoNote: {
    color: colors.subtle,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginTop: 10,
    marginBottom: 17,
  },
  stats: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 19,
    padding: 14,
    marginBottom: 30,
    borderWidth: 1,
    borderColor: colors.line,
  },
  stat: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 7 },
  statIcon: {
    width: 35,
    height: 35,
    borderRadius: 12,
    backgroundColor: colors.pale,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statSeparator: {
    width: 1,
    height: 27,
    backgroundColor: colors.line,
    marginHorizontal: 5,
  },
  statValue: { fontSize: 15, fontWeight: '800', color: colors.ink },
  statLabel: { fontSize: 10, color: colors.muted, marginTop: 3 },
  reviewCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 13,
    gap: 15,
    borderRadius: 21,
    backgroundColor: colors.surface,
    marginBottom: 27,
  },
  reviewArt: {
    width: 74,
    height: 84,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.pale,
  },
  reviewArtText: { color: colors.forest, fontSize: 29, fontWeight: '800' },
  reviewTitle: { fontSize: 16, fontWeight: '800', color: colors.ink },
  reviewSubtitle: { fontSize: 12, color: colors.muted },
  reviewLink: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.success,
    marginTop: 5,
  },
  cameraPhoto: {
    height: 294,
    overflow: 'hidden',
    borderRadius: 24,
    backgroundColor: colors.pale,
  },
  cameraImage: { width: '100%', height: '100%' },
  cameraTag: {
    position: 'absolute',
    top: 14,
    left: 14,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 18,
  },
  cameraTagText: {
    fontSize: 10,
    fontWeight: '800',
    color: colors.forest,
    letterSpacing: 1,
  },
  cameraHint: {
    position: 'absolute',
    bottom: 15,
    left: 15,
    right: 15,
    backgroundColor: '#14392FE8',
    padding: 11,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cameraHintText: {
    color: colors.surface,
    fontSize: 11,
    fontWeight: '700',
    flex: 1,
  },
  captureRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 29,
    alignItems: 'center',
    marginTop: 19,
  },
  captureSide: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.line,
  },
  shutter: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: colors.forest,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 5,
    borderColor: colors.lime,
  },
  cameraCaption: {
    fontSize: 12,
    textAlign: 'center',
    color: colors.muted,
    marginTop: 12,
    marginBottom: 18,
  },
  scenePicker: { gap: 8, paddingRight: 22 },
  resultImageWrap: {
    height: 226,
    borderRadius: 22,
    overflow: 'hidden',
    backgroundColor: colors.pale,
    marginBottom: 16,
  },
  resultImage: { width: '100%', height: '100%' },
  resultOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#14392FDD',
    padding: 16,
    gap: 5,
  },
  resultImageTitle: { fontSize: 21, fontWeight: '800', color: colors.surface },
  resultInfo: {
    flexDirection: 'row',
    gap: 11,
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: 14,
    marginBottom: 13,
  },
  resultInfoIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: colors.lime,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultInfoTitle: { fontSize: 15, color: colors.ink, fontWeight: '800' },
  resultInfoCaption: { fontSize: 12, color: colors.muted, marginTop: 4 },
  notice: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
    backgroundColor: colors.pale,
    borderRadius: 14,
    padding: 13,
    marginBottom: 27,
  },
  noticeText: { flex: 1, color: colors.forest, fontSize: 12, lineHeight: 19 },
  objectList: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20 },
  objectTag: { backgroundColor: colors.surface, borderColor: colors.line, borderWidth: 1, borderRadius: 20, paddingHorizontal: 12, paddingVertical: 8 },
  objectTagText: { color: colors.forest, fontSize: 12, fontWeight: '700' },
  wordFeature: {
    backgroundColor: colors.forest,
    borderRadius: 25,
    padding: 23,
    minHeight: 190,
    marginBottom: 27,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'flex-start',
    gap: 10,
  },
  levelPill: {
    borderRadius: 12,
    backgroundColor: colors.lime,
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  levelText: { fontSize: 11, color: colors.forest, fontWeight: '800' },
  bigWord: {
    color: colors.surface,
    fontSize: 40,
    fontWeight: '800',
    letterSpacing: -1,
    maxWidth: '100%',
  },
  ipa: { color: colors.lime, fontSize: 16 },
  wordWatermark: {
    position: 'absolute',
    right: -18,
    bottom: -35,
    fontSize: 96,
    color: '#FFFFFF13',
    fontWeight: '800',
  },
  detailBlock: { gap: 11, marginBottom: 25 },
  meaning: { color: colors.ink, fontWeight: '800', fontSize: 28 },
  example: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: 17,
    gap: 11,
    borderLeftWidth: 3,
    borderLeftColor: colors.lime,
  },
  exampleEnglish: {
    fontSize: 17,
    lineHeight: 25,
    color: colors.ink,
    fontWeight: '700',
  },
  exampleVietnamese: { fontSize: 13, lineHeight: 20, color: colors.muted },
  tip: {
    flexDirection: 'row',
    gap: 10,
    backgroundColor: colors.pale,
    borderRadius: 17,
    padding: 15,
  },
  tipText: { flex: 1, fontSize: 14, lineHeight: 21, color: colors.ink },
  source: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    borderRadius: 18,
    backgroundColor: colors.surface,
    padding: 10,
  },
  sourceImage: { width: 54, height: 54, borderRadius: 11 },
  sourceTitle: { fontSize: 15, fontWeight: '800', color: colors.ink },
  sourceCaption: { fontSize: 12, color: colors.muted, marginTop: 4 },
  topBarActions: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  audioBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: colors.pale,
    alignItems: 'center',
    justifyContent: 'center',
  },
  audioBtnDisabled: { opacity: 0.4 },
  ipaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 2,
  },
});
