import { StyleSheet } from 'react-native';
import { colors } from '@/theme/theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  loading: { flex: 1, backgroundColor: colors.background, alignItems: 'center', justifyContent: 'center' },
  scrollContent: { flexGrow: 1 },
  tabBar: {
    minHeight: 70,
    flexDirection: 'row',
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.line,
    paddingTop: 6,
  },
  tab: {
    flex: 1,
    minHeight: 60,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  pressed: { opacity: 0.7 },
  tabIcon: {
    width: 37,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
  },
  activeTabIcon: { backgroundColor: colors.pale },
  cameraTab: {
    width: 42,
    height: 42,
    borderRadius: 15,
    backgroundColor: colors.forest,
    marginTop: -8,
  },
  tabLabel: { color: colors.subtle, fontSize: 10, fontWeight: '700' },
  activeTabLabel: { color: colors.forest, fontWeight: '800' },
  toast: {
    position: 'absolute',
    left: 24,
    right: 24,
    minHeight: 45,
    borderRadius: 14,
    backgroundColor: colors.deep,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    elevation: 6,
    shadowColor: colors.deep,
    shadowOpacity: 0.18,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 8 },
  },
  toastWithTabs: { bottom: 78 },
  toastWithoutTabs: { bottom: 12 },
  toastText: {
    color: colors.surface,
    fontSize: 13,
    fontWeight: '700',
    flex: 1,
  },
});
