import { StyleSheet } from 'react-native';
import { colors } from '@/theme/theme';

export const styles = StyleSheet.create({
  fill: { flex: 1 },
  page: { paddingHorizontal: 22, paddingTop: 12, paddingBottom: 32 },
  identity: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 17,
    gap: 13,
    backgroundColor: colors.surface,
    borderRadius: 20,
    marginBottom: 17,
  },
  avatar: {
    width: 54,
    height: 54,
    borderRadius: 18,
    backgroundColor: colors.lime,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarLetter: { fontSize: 23, color: colors.forest, fontWeight: '800' },
  identityName: { fontSize: 17, fontWeight: '800', color: colors.ink },
  identitySub: { fontSize: 12, color: colors.muted, marginTop: 4 },
  profileStats: {
    flexDirection: 'row',
    backgroundColor: colors.forest,
    borderRadius: 20,
    marginBottom: 29,
    padding: 22,
    alignItems: 'center',
  },
  stat: { flex: 1, alignItems: 'center', gap: 3 },
  statValue: { fontSize: 28, fontWeight: '800', color: colors.lime },
  statCaption: { color: colors.surface, fontSize: 12 },
  verticalLine: { backgroundColor: '#FFFFFF40', width: 1, height: 32 },
  menu: {
    marginTop: 12,
    marginBottom: 28,
    borderRadius: 19,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  menuItem: {
    minHeight: 61,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.line,
  },
  menuIcon: {
    width: 35,
    height: 35,
    backgroundColor: colors.pale,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuText: { fontSize: 14, fontWeight: '700', color: colors.ink },
  menuHint: { fontSize: 11, color: colors.muted, marginTop: 3 },
  footer: { alignItems: 'center', paddingTop: 7, gap: 11 },
  footerText: {
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
    color: colors.muted,
  },
  onboardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  skip: {
    minWidth: 65,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  skipText: { color: colors.muted, fontWeight: '700', fontSize: 13 },
  onboardImage: {
    width: '100%',
    height: 290,
    borderRadius: 26,
    marginBottom: 28,
  },
  onboardText: { gap: 15 },
  onboardTitle: {
    fontSize: 31,
    lineHeight: 38,
    fontWeight: '800',
    letterSpacing: -0.6,
    color: colors.ink,
  },
  onboardDescription: { color: colors.muted, fontSize: 15, lineHeight: 23 },
  dots: { flexDirection: 'row', gap: 7, marginVertical: 19 },
  dot: { width: 23, height: 8, borderRadius: 5, backgroundColor: colors.line },
  activeDot: { width: 35, backgroundColor: colors.forest },
  authGraphic: {
    marginTop: 59,
    marginBottom: 35,
    width: 120,
    height: 120,
    borderRadius: 42,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.lime,
  },
  authTitle: {
    fontSize: 33,
    lineHeight: 41,
    color: colors.ink,
    fontWeight: '800',
    marginBottom: 15,
  },
  authDescription: {
    fontSize: 15,
    lineHeight: 24,
    color: colors.muted,
    marginBottom: 30,
  },
  authInput: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 13, paddingHorizontal: 16, minHeight: 54, color: colors.ink, fontSize: 15, marginBottom: 12 },
  authError: { color: colors.error, fontSize: 13, marginBottom: 14 },
  authSwitch: { padding: 15, alignItems: 'center', marginBottom: 12 },
  authSwitchText: { color: colors.forest, fontWeight: '700' },
  authNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    backgroundColor: colors.pale,
    borderRadius: 17,
    marginBottom: 25,
  },
  authNoticeText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 20,
    color: colors.forest,
  },
});
